/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#include "../s21_matrix.h"

START_TEST(create_matrix_1) {
  matrix_t matrix;
  int flag = s21_create_matrix(1, 1, &matrix);
  matrix.matrix[0][0] = 1;

  ck_assert_int_eq(flag, 0);
  ck_assert_int_eq(matrix.rows, 1);
  ck_assert_int_eq(matrix.columns, 1);
  ck_assert_int_eq(matrix.matrix[0][0], 1);

  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(create_matrix_2) {
  matrix_t matrix;
  int flag = s21_create_matrix(2, 2, &matrix);
  matrix.matrix[0][0] = 2;

  ck_assert_int_eq(flag, 0);
  ck_assert_int_eq(matrix.rows, 2);
  ck_assert_int_eq(matrix.columns, 2);
  ck_assert_int_eq(matrix.matrix[0][0], 2);

  s21_remove_matrix(&matrix);
}
END_TEST

START_TEST(create_matrix_3) {
  matrix_t matrix;
  int flag = s21_create_matrix(0, 0, &matrix);

  ck_assert_int_eq(flag, 1);
}
END_TEST

START_TEST(eq_matrix_1) {
  matrix_t matrix1;
  matrix_t matrix2;
  int flag1 = s21_create_matrix(3, 3, &matrix1);
  int flag2 = s21_create_matrix(3, 3, &matrix2);
  ck_assert_int_eq(flag1, flag2);

  int res = s21_eq_matrix(&matrix1, &matrix2);
  ck_assert_int_eq(1, res);

  int count = 1;
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      matrix1.matrix[i][j] = count;
      matrix2.matrix[i][j] = count;
      count++;
    }
  }
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      ck_assert_double_eq(matrix1.matrix[i][j], matrix2.matrix[i][j]);
    }
  }
  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(eq_matrix_2) {
  matrix_t matrix1;
  matrix_t matrix2;
  int flag1 = s21_create_matrix(3, 3, &matrix1);
  int flag2 = s21_create_matrix(3, 3, &matrix2);

  matrix1.matrix[0][0] = 0.0000002;
  matrix2.matrix[0][0] = 0.0000001;

  int res = s21_eq_matrix(&matrix1, &matrix2);
  ck_assert_int_eq(0, res);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(eq_matrix_3) {
  matrix_t matrix1;
  matrix_t matrix2;
  int flag1 = s21_create_matrix(1, 3, &matrix1);
  int flag2 = s21_create_matrix(2, 3, &matrix2);
  ck_assert_int_eq(flag1, flag2);

  int res = s21_eq_matrix(&matrix1, &matrix2);
  ck_assert_int_eq(0, res);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(sum_matrix_1) {
  matrix_t matrix1;
  matrix_t matrix2;
  matrix_t matrix3;
  int flag1 = s21_create_matrix(3, 3, &matrix1);
  int flag2 = s21_create_matrix(3, 3, &matrix2);

  ck_assert_int_eq(flag1, flag2);

  int count = 1;
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      matrix1.matrix[i][j] = count;
      matrix2.matrix[i][j] = count;
    }
  }
  int res = s21_sum_matrix(&matrix1, &matrix2, &matrix3);
  ck_assert_int_eq(0, res);

  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      ck_assert_double_eq(matrix3.matrix[i][j], 2);
    }
  }

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&matrix3);
}
END_TEST

START_TEST(sum_matrix_2) {
  matrix_t matrix1;
  matrix_t matrix2;
  matrix_t matrix3;
  int flag1 = s21_create_matrix(1, 3, &matrix1);
  int flag2 = s21_create_matrix(2, 3, &matrix2);

  ck_assert_int_eq(flag1, flag2);

  int res = s21_sum_matrix(&matrix1, &matrix2, &matrix3);
  ck_assert_int_eq(2, res);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(sum_matrix_3) {
  matrix_t matrix1;
  matrix_t matrix2;
  matrix_t matrix3;
  int flag1 = s21_create_matrix(1, 3, &matrix1);
  matrix2.matrix = NULL;

  int res = s21_sum_matrix(&matrix1, &matrix2, &matrix3);
  ck_assert_int_eq(1, res);

  s21_remove_matrix(&matrix1);
}
END_TEST

START_TEST(sub_matrix_1) {
  matrix_t matrix1;
  matrix_t matrix2;
  matrix_t matrix3;
  int flag1 = s21_create_matrix(3, 3, &matrix1);
  int flag2 = s21_create_matrix(3, 3, &matrix2);

  ck_assert_int_eq(flag1, flag2);

  int count = 1;
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      matrix1.matrix[i][j] = count;
      matrix2.matrix[i][j] = count;
    }
  }
  int res = s21_sub_matrix(&matrix1, &matrix2, &matrix3);
  ck_assert_int_eq(0, res);

  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      ck_assert_double_eq(matrix3.matrix[i][j], 0);
    }
  }

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&matrix3);
}
END_TEST

START_TEST(sub_matrix_2) {
  matrix_t matrix1;
  matrix_t matrix2;
  matrix_t matrix3;
  int flag1 = s21_create_matrix(1, 3, &matrix1);
  int flag2 = s21_create_matrix(2, 3, &matrix2);

  ck_assert_int_eq(flag1, flag2);

  int res = s21_sub_matrix(&matrix1, &matrix2, &matrix3);
  ck_assert_int_eq(2, res);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(sub_matrix_3) {
  matrix_t matrix1;
  matrix_t matrix2;
  matrix_t matrix3;
  int flag1 = s21_create_matrix(1, 3, &matrix1);
  matrix2.matrix = NULL;

  int res = s21_sub_matrix(&matrix1, &matrix2, &matrix3);
  ck_assert_int_eq(1, res);

  s21_remove_matrix(&matrix1);
}
END_TEST

START_TEST(mult_number_1) {
  matrix_t matrix1;
  matrix_t matrix2;

  int flag1 = s21_create_matrix(3, 3, &matrix1);

  int count = 1;
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      matrix1.matrix[i][j] = count;
    }
  }

  int res = s21_mult_number(&matrix1, 2, &matrix2);
  ck_assert_int_eq(0, res);

  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      ck_assert_double_eq(matrix2.matrix[i][j], 2);
    }
  }

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(mult_number_2) {
  matrix_t matrix1;
  matrix_t matrix2;

  matrix1.matrix = NULL;

  int res = s21_mult_number(&matrix1, 2, &matrix2);
  ck_assert_int_eq(1, res);
}
END_TEST

START_TEST(mult_matrix_1) {
  matrix_t matrix1;
  matrix_t matrix2;
  matrix_t matrix3;

  int flag1 = s21_create_matrix(3, 3, &matrix1);
  int flag2 = s21_create_matrix(3, 3, &matrix2);

  int count = 1;
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      matrix1.matrix[i][j] = count;
      count++;
    }
  }
  count = 1;
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      matrix2.matrix[i][j] = count;
      count++;
    }
  }

  int res = s21_mult_matrix(&matrix1, &matrix2, &matrix3);
  ck_assert_int_eq(0, res);

  ck_assert_double_eq(matrix3.matrix[0][0], 30);
  ck_assert_double_eq(matrix3.matrix[0][1], 36);
  ck_assert_double_eq(matrix3.matrix[0][2], 42);
  ck_assert_double_eq(matrix3.matrix[1][0], 66);
  ck_assert_double_eq(matrix3.matrix[1][1], 81);
  ck_assert_double_eq(matrix3.matrix[1][2], 96);
  ck_assert_double_eq(matrix3.matrix[2][0], 102);
  ck_assert_double_eq(matrix3.matrix[2][1], 126);
  ck_assert_double_eq(matrix3.matrix[2][2], 150);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&matrix3);
}
END_TEST

START_TEST(mult_matrix_2) {
  matrix_t matrix1;
  matrix_t matrix2;
  matrix_t matrix3;

  int flag1 = s21_create_matrix(2, 2, &matrix1);
  int flag2 = s21_create_matrix(2, 2, &matrix2);

  int count = 1;
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      matrix1.matrix[i][j] = count;
      count++;
    }
  }
  count = 1;
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 2; j++) {
      matrix2.matrix[i][j] = count;
      count++;
    }
  }

  int res = s21_mult_matrix(&matrix1, &matrix2, &matrix3);
  ck_assert_int_eq(0, res);

  ck_assert_double_eq(matrix3.matrix[0][0], 7);
  ck_assert_double_eq(matrix3.matrix[0][1], 10);
  ck_assert_double_eq(matrix3.matrix[1][0], 15);
  ck_assert_double_eq(matrix3.matrix[1][1], 22);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&matrix3);
}
END_TEST

START_TEST(mult_matrix_3) {
  matrix_t matrix1;
  matrix_t matrix2;
  matrix_t matrix3;

  int flag1 = s21_create_matrix(1, 1, &matrix1);
  int flag2 = s21_create_matrix(1, 1, &matrix2);

  matrix1.matrix[0][0] = 2;
  matrix2.matrix[0][0] = 2;

  int res = s21_mult_matrix(&matrix1, &matrix2, &matrix3);

  ck_assert_int_eq(0, res);

  ck_assert_double_eq(matrix3.matrix[0][0], 4);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
  s21_remove_matrix(&matrix3);
}
END_TEST

START_TEST(mult_matrix_4) {
  matrix_t matrix1;
  matrix_t matrix2;
  matrix_t matrix3;

  int flag1 = s21_create_matrix(1, 1, &matrix1);
  matrix2.matrix = NULL;

  int res = s21_mult_matrix(&matrix1, &matrix2, &matrix3);

  ck_assert_int_eq(1, res);

  s21_remove_matrix(&matrix1);
}
END_TEST

START_TEST(mult_matrix_5) {
  matrix_t matrix1;
  matrix_t matrix2;
  matrix_t matrix3;

  int flag1 = s21_create_matrix(1, 2, &matrix1);
  int flag2 = s21_create_matrix(3, 1, &matrix2);

  matrix1.matrix[0][0] = 2;
  matrix2.matrix[0][0] = 2;

  int res = s21_mult_matrix(&matrix1, &matrix2, &matrix3);

  ck_assert_int_eq(2, res);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(transpose_1) {
  matrix_t matrix1;
  matrix_t matrix2;

  int flag = s21_create_matrix(2, 3, &matrix1);

  int count = 1;
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 3; j++) {
      matrix1.matrix[i][j] = count;
      count++;
    }
  }

  int res = s21_transpose(&matrix1, &matrix2);

  ck_assert_int_eq(0, res);

  ck_assert_int_eq(3, matrix2.rows);
  ck_assert_int_eq(2, matrix2.columns);

  ck_assert_double_eq(matrix2.matrix[0][0], 1);
  ck_assert_double_eq(matrix2.matrix[0][1], 4);
  ck_assert_double_eq(matrix2.matrix[1][0], 2);
  ck_assert_double_eq(matrix2.matrix[1][1], 5);
  ck_assert_double_eq(matrix2.matrix[2][0], 3);
  ck_assert_double_eq(matrix2.matrix[2][1], 6);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(transpose_2) {
  matrix_t matrix1;
  matrix_t matrix2;

  matrix1.matrix = NULL;

  int res = s21_transpose(&matrix1, &matrix2);

  ck_assert_int_eq(1, res);
}
END_TEST

START_TEST(calc_complements_1) {
  matrix_t matrix1;
  matrix_t matrix2;

  int flag = s21_create_matrix(3, 3, &matrix1);

  matrix1.matrix[0][0] = 1;
  matrix1.matrix[0][1] = 2;
  matrix1.matrix[0][2] = 3;
  matrix1.matrix[1][0] = 0;
  matrix1.matrix[1][1] = 4;
  matrix1.matrix[1][2] = 2;
  matrix1.matrix[2][0] = 5;
  matrix1.matrix[2][1] = 2;
  matrix1.matrix[2][2] = 1;

  int res = s21_calc_complements(&matrix1, &matrix2);

  ck_assert_int_eq(0, res);

  ck_assert_double_eq(matrix2.matrix[0][0], 0);
  ck_assert_double_eq(matrix2.matrix[0][1], 10);
  ck_assert_double_eq(matrix2.matrix[0][2], -20);
  ck_assert_double_eq(matrix2.matrix[1][0], 4);
  ck_assert_double_eq(matrix2.matrix[1][1], -14);
  ck_assert_double_eq(matrix2.matrix[1][2], 8);
  ck_assert_double_eq(matrix2.matrix[2][0], -8);
  ck_assert_double_eq(matrix2.matrix[2][1], -2);
  ck_assert_double_eq(matrix2.matrix[2][2], 4);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(calc_complements_2) {
  matrix_t matrix1;
  matrix_t matrix2;

  int flag = s21_create_matrix(1, 1, &matrix1);

  matrix1.matrix[0][0] = 1;

  int res = s21_calc_complements(&matrix1, &matrix2);

  ck_assert_int_eq(0, res);

  ck_assert_double_eq(matrix2.matrix[0][0], 1);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(calc_complements_3) {
  matrix_t matrix1;
  matrix_t matrix2;

  matrix1.matrix = NULL;

  int res = s21_calc_complements(&matrix1, &matrix2);

  ck_assert_int_eq(1, res);
}
END_TEST

START_TEST(calc_complements_4) {
  matrix_t matrix1;
  matrix_t matrix2;

  int flag = s21_create_matrix(2, 3, &matrix1);

  int res = s21_calc_complements(&matrix1, &matrix2);

  ck_assert_int_eq(2, res);

  s21_remove_matrix(&matrix1);
}
END_TEST

START_TEST(determinant_1) {
  matrix_t matrix1;
  double result = 0;
  int flag = s21_create_matrix(3, 3, &matrix1);

  int count = 1;
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 3; j++) {
      matrix1.matrix[i][j] = count;
      count++;
    }
  }

  int res = s21_determinant(&matrix1, &result);

  ck_assert_int_eq(0, res);
  ck_assert_double_eq(0, result);

  s21_remove_matrix(&matrix1);
}
END_TEST

START_TEST(determinant_2) {
  matrix_t matrix1;
  double result = 0;

  matrix1.matrix = NULL;

  int res = s21_determinant(&matrix1, &result);

  ck_assert_int_eq(1, res);
}
END_TEST

START_TEST(determinant_3) {
  matrix_t matrix1;
  double result = 0;

  int flag = s21_create_matrix(2, 3, &matrix1);

  int res = s21_determinant(&matrix1, &result);

  ck_assert_int_eq(2, res);

  s21_remove_matrix(&matrix1);
}
END_TEST

START_TEST(inverse_matrix_1) {
  matrix_t matrix1;
  matrix_t matrix2;

  int flag = s21_create_matrix(3, 3, &matrix1);

  matrix1.matrix[0][0] = 2;
  matrix1.matrix[0][1] = 5;
  matrix1.matrix[0][2] = 7;
  matrix1.matrix[1][0] = 6;
  matrix1.matrix[1][1] = 3;
  matrix1.matrix[1][2] = 4;
  matrix1.matrix[2][0] = 5;
  matrix1.matrix[2][1] = -2;
  matrix1.matrix[2][2] = -3;

  int res = s21_inverse_matrix(&matrix1, &matrix2);

  ck_assert_int_eq(0, res);

  ck_assert_double_eq(matrix2.matrix[0][0], 1);
  ck_assert_double_eq(matrix2.matrix[0][1], -1);
  ck_assert_double_eq(matrix2.matrix[0][2], 1);
  ck_assert_double_eq(matrix2.matrix[1][0], -38);
  ck_assert_double_eq(matrix2.matrix[1][1], 41);
  ck_assert_double_eq(matrix2.matrix[1][2], -34);
  ck_assert_double_eq(matrix2.matrix[2][0], 27);
  ck_assert_double_eq(matrix2.matrix[2][1], -29);
  ck_assert_double_eq(matrix2.matrix[2][2], 24);

  s21_remove_matrix(&matrix1);
  s21_remove_matrix(&matrix2);
}
END_TEST

START_TEST(inverse_matrix_2) {
  matrix_t matrix1;
  matrix_t matrix2;

  matrix1.matrix = NULL;

  int res = s21_inverse_matrix(&matrix1, &matrix2);

  ck_assert_int_eq(1, res);
}
END_TEST

START_TEST(inverse_matrix_3) {
  matrix_t matrix1;
  matrix_t matrix2;

  int flag = s21_create_matrix(2, 3, &matrix1);

  int res = s21_inverse_matrix(&matrix1, &matrix2);

  ck_assert_int_eq(2, res);

  s21_remove_matrix(&matrix1);
}
END_TEST

START_TEST(inverse_matrix_4) {
  matrix_t matrix1;
  matrix_t matrix2;

  int flag = s21_create_matrix(3, 3, &matrix1);

  int count = 1;
  for (int i = 0; i < 2; i++) {
    for (int j = 0; j < 3; j++) {
      matrix1.matrix[i][j] = count;
      count++;
    }
  }

  int res = s21_inverse_matrix(&matrix1, &matrix2);

  ck_assert_int_eq(2, res);

  s21_remove_matrix(&matrix1);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, create_matrix_1);
  tcase_add_test(tc1_1, create_matrix_2);
  tcase_add_test(tc1_1, create_matrix_3);
  tcase_add_test(tc1_1, eq_matrix_1);
  tcase_add_test(tc1_1, eq_matrix_2);
  tcase_add_test(tc1_1, eq_matrix_3);
  tcase_add_test(tc1_1, sum_matrix_1);
  tcase_add_test(tc1_1, sum_matrix_2);
  tcase_add_test(tc1_1, sum_matrix_3);
  tcase_add_test(tc1_1, sub_matrix_1);
  tcase_add_test(tc1_1, sub_matrix_2);
  tcase_add_test(tc1_1, sub_matrix_3);
  tcase_add_test(tc1_1, mult_number_1);
  tcase_add_test(tc1_1, mult_number_2);
  tcase_add_test(tc1_1, mult_matrix_1);
  tcase_add_test(tc1_1, mult_matrix_2);
  tcase_add_test(tc1_1, mult_matrix_3);
  tcase_add_test(tc1_1, mult_matrix_4);
  tcase_add_test(tc1_1, mult_matrix_5);
  tcase_add_test(tc1_1, transpose_1);
  tcase_add_test(tc1_1, transpose_2);
  tcase_add_test(tc1_1, calc_complements_1);
  tcase_add_test(tc1_1, calc_complements_2);
  tcase_add_test(tc1_1, calc_complements_3);
  tcase_add_test(tc1_1, calc_complements_4);
  tcase_add_test(tc1_1, determinant_1);
  tcase_add_test(tc1_1, determinant_2);
  tcase_add_test(tc1_1, determinant_3);
  tcase_add_test(tc1_1, inverse_matrix_1);
  tcase_add_test(tc1_1, inverse_matrix_2);
  tcase_add_test(tc1_1, inverse_matrix_3);
  tcase_add_test(tc1_1, inverse_matrix_4);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
